name: Create Pull Request from feature to main

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install GitHub CLI
      run: |
        npm install -g @githubnext/github

    - name: Create Pull Request using gh
      run: |
        gh pr create --base main --head ${{ github.ref_name }} --title "PR automático de ${{ github.ref_name }} para main" --body "Este é um PR automático de ${{ github.ref_name }} para main."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
