name: Create Pull Request from feature to main

on:
  push:
    branches:
      - 'feature/**'

permissions:
  contents: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Check if PR exists
      id: check_pr
      run: |
        gh pr list --base main --head ${{ github.ref_name }} --state open
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Create Pull Request if none exists
      if: ${{ steps.check_pr.outputs.exit_code }} == '1'
      run: |
        gh pr create --base main --head ${{ github.ref_name }} --title "PR automático de ${{ github.ref_name }} para main" --body "Este é um PR automático de ${{ github.ref_name }} para main."
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
